#!/bin/bash
#
# aliases.sh
#
# Josh Newman - 2014
#

# SHOW/HIDE FILES
alias showfiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hidefiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'

# SHOW/HIDE DESKTOP
alias showDesktop='defaults write com.apple.finder CreateDesktop true && killall Finder'
alias hideDesktop='defaults write com.apple.finder CreateDesktop false && killall Finder'

# DISPLAYING FILES/FOLDERS
alias tree='tree -ACL 2 --dirsfirst'
alias CAT='pygmentize -0 style=monokai -f console256 -g'
alias ls='command ls -G'
alias ll='ls -la'

# UPDATING AND RELOADING
alias reload='source ~/.dotfiles/.zshrc && sh ~/.dotfiles/makesymlinks.sh'

# EDITING FILES
alias sl='atom -n'
alias zshrc='atom ~/.zshrc'
alias dotfiles='atom ~/.dotfiles'
