#!/bin/bash
#
# exports.sh
#
# Josh Newman - 2014
#


# SCRIPTS PATH
export PATH=$HOME/.dotfiles/scripts

# PATH EXPORT
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:$PATH"

# YARN
export PATH="$HOME/.yarn/bin:$PATH"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
 export EDITOR='vim'
else
 export EDITOR='subl'
fi
