#!/bin/bash
#
# exports.sh
#
# Josh Newman - 2014
#

# JAVA DERBY PATHS
export DERBY_INSTALL=/opt/Apache/db-derby-10.10.1.1-bin
export DERBY_HOME=$DERBY_INSTALL
export HIBERNATE_HOME=/opt/Hibernate/hibernate-release-4.3.5/lib/required
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home
export PATH=$JAVA_HOME/bin:$PATH
## classpaths for derby
export CLASSPATH=$DERBY_INSTALL/lib/derby.jar:$DERBY_INSTALL/lib/derbytools.jar:$DERBY_INSTALL/lib/derbynet.jar:$DERBY_INSTALL/lib/derbyclient.jar:$DERBY_INSTALL/lib/derbyrun.jar:$DERBY_INSTALL/lib/derby.war
## classpaths for hibernate
export CLASSPATH=$CLASSPATH:$HIBERNATE_HOME/antlr-2.7.7.jar:$HIBERNATE_HOME/dom4j-1.6.1.jar:$HIBERNATE_HOME/hibernate-commons-annotations-4.0.4.Final.jar:$HIBERNATE_HOME/hibernate-core-4.3.5.Final.jar:$HIBERNATE_HOME/hibernate-jpa-2.1-api-1.0.0.Final.jar:$HIBERNATE_HOME/jandex-1.1.0.Final.jar:$HIBERNATE_HOME/javassist-3.18.1-GA.jar:$HIBERNATE_HOME/jboss-logging-3.1.3.GA.jar:$HIBERNATE_HOME/jboss-logging-annotations-1.2.0.Beta1.jar:$HIBERNATE_HOME/jboss-transaction-api_1.2_spec-1.0.0.Final.jar:./

# MASSIVE PATH EXPORT
export PATH="/usr/local/opt/php56/bin:/Users/josh/.rvm/gems/ruby-2.1.0/bin:/Users/josh/.rvm/gems/ruby-2.1.0@global/bin:/Users/josh/.rvm/rubies/ruby-2.1.0/bin:/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/bin:/Applications/Postgres93.app/Contents/MacOS/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Users/josh/.rvm/bin"

# FOLDER PATHS
export RAILS_WORKSPACE='~/Dropbox/Development/Rails_Workspace'
export DB_WORKSPACE=~/Google\ Drive/University\ Work/2014_Sem1/3612ICT_Database\ Systems\ and\ Admin/

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
 export EDITOR='vim'
else
 export EDITOR='subl'
fi
