#!/bin/bash

# Written by Bram Neijt
# [http://bneijt.nl/blog/post/webcam-picture-on-every-git-commit/]

/usr/bin/git "$@"
ESTATUS="$?"
if [ "$ESTATUS" = "0" ]; then
    if [ "$1" = "commit" ]; then
        webcamsnapshot "git commit"
    fi
fi
exit "${ESTATUS}"
