#!/bin/bash

# Written by Bram Neijt
# [http://bneijt.nl/blog/post/webcam-picture-on-every-git-commit/]

/usr/bin/git "$@"
ESTATUS="$?"
if [ "$ESTATUS" = "0" ]; then
    ALIASES="`cat ~/.dotfiles/gitconfig | grep ' commit ' | awk '{print $1;}'`"
    ARG_FOUND="`echo $ALIASES | grep $1`"

    if [ "$1" = "commit" ] || [ "$1" = "$ARG_FOUND" ]; then
      webcamsnapshot "git commit"
    fi
fi
exit "${ESTATUS}"

# $ cat gitconfig | grep " commit " | awk '{print $1;}'
